### ISSUE TITLE
Directing issues to sktime main repo?

### ISSUE THREAD

**Issue by fkiraly** [conda-forge/sktime-feedstock#36]
### Comment:

Should this issue tracker not direct bug reports and issues to the main sktime repo?

We probably missed this issue here
https://github.com/conda-forge/sktime-feedstock/issues/31
because no one was watching this one?
(which makes sense since it's the repo of a secondary distribution channel)

**Comment by fkiraly** [comment]
Depending on whether we want this, how would that technically work?

**Comment by lmmentel** [comment]
What do you mean missed? I responded to the issue.

**Comment by fkiraly** [comment]
well, 3 weeks latency? Not criticizing since we're volunteers, but I was trying to infer how much of this latency was due to "not seeing it"?

**Comment by fkiraly** [comment]
@lmmentel has everything perfectly under control 😄 (see more recent issues), so no need for thinking of any added process imo
