### ISSUE TITLE
0.11 not built for osx-arm64

### ISSUE THREAD

**Issue by jonashaag** [conda-forge/sktime-feedstock#39]
There seems to be a 0.10 noarch build but no 0.11.

**Comment by lmmentel** [comment]
Thanks for raising this @jonashaag. I remember flagging the builds as `noarch` but it must've been updated. I'll investigate and let you know.

**Comment by glemaitre** [comment]
Since #43 has been merged, it might be enough to close this PR. 0.11 is not available but 0.12 will be.
