### ISSUE TITLE
[MNT] Include python 3.10 in CI worfklows

### ISSUE THREAD

**Issue by lmmentel** [conda-forge/sktime-feedstock#47]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Recently sktime extended support to python 3.10, however the CI pipelines in the repo do not cover python 3.10.

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

**Comment by giswqs** [comment]
It would be great to add support for Python 3.10. It is currently a roadblocker for downstream packages such as autogluon.timesries https://github.com/conda-forge/autogluon.timeseries-feedstock/pull/9

@gradientsky @Innixma @dhirschfeld

**Comment by dhirschfeld** [comment]
Resolved by #64
