### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by fkiraly** [conda-forge/sktime-feedstock#66]
We should ensure that 0.16.1 gets properly released with 3.11 support on `conda-forge`.

@dhirschfeld, @giswqs, thanks for your contribution!

I'm not 100% clear about the status, CI does seem to confirm 3.10 only and the 3.11 install still does not work locally.

Do you have a good picture of what we'd need to do, and what the blockers are? How can I help?

**Comment by giswqs** [comment]
See https://github.com/conda-forge/sktime-feedstock/pull/65#issuecomment-1439234927

**Comment by fkiraly** [comment]
Ok, can you kindly confirm my understanding, @giswqs?

* there is an "3.11 migration" which is sth all packages on conda-forge are undergoing, and it's a process currently underway
* packages can "migrate" only if their dependencies have already migrated
* dependencies of `sktime` have not yet migrated

?

If so, where can I see the dependencies we are still waiting for?

**Comment by dhirschfeld** [comment]
That's correct.

A migration is just a rebuild of the entire ecosystem in reverse dependency order.

When the dependencies of your package have been built for py311, your package will then be built for py311.

I don't know of an easy way to view the status of all of your dependencies other than by looking them up individually.

**Comment by fkiraly** [comment]
> I don't know of an easy way to view the status of all of your dependencies other than by looking them up individually.

My concern is that `numba` is somehow an assumed dependency in 3.11 in the "migration", because it's not understanding python version conditional dependencies correctly (`numba` is a core dependency only on python 3.7-3.10). Do you know a way to rule this out?

**Comment by dhirschfeld** [comment]
> because it's not understanding python version conditional dependencies correctly

In the recipe here `numba >=0.53` is an absolute requirement:
https://github.com/conda-forge/sktime-feedstock/blob/e8b1049388e5e24dc5ce0169dc659aab3a08e2a7/recipe/meta.yaml#L47

**Comment by fkiraly** [comment]
ahhhhhh

**Comment by fkiraly** [comment]
that's what I was suspecting. What's the syntax to turn it into a conditional requirement, i.e., only on 3.7-3.10?

Alternatively, we could also add a recipe `sktime-wo-numba` that does not have it as a requirement, `sktime` would still run.

**Comment by fkiraly** [comment]
reading this, but I'm not getting the information I'm looking for yet ...
https://conda-forge.org/docs/maintainer/adding_pkgs.html#requirements

**Comment by fkiraly** [comment]
looks like a `project.toml`, what if we replace the offending line with `numba>=0.53; python_version < '3.11'`? Would that work?

**Comment by dhirschfeld** [comment]
The way you do it with conda is using a `# [py<311]` [selector](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors)

e.g. https://github.com/conda-forge/polars-feedstock/blob/f48b2daf8b78285e44268416f9a7a81e62a681d6/recipe/meta.yaml#L37

**Comment by fkiraly** [comment]
like this?
https://github.com/conda-forge/sktime-feedstock/pull/67

**Comment by fkiraly** [comment]
augh, it wants me to fork first...

**Comment by fkiraly** [comment]
why is this not testing 3.11?
https://github.com/conda-forge/sktime-feedstock/pull/68

**Comment by dhirschfeld** [comment]
It will still need to be migrated to py311. With the conditional `numpy` requirement the bot may make a PR in the next several days.

**Comment by fkiraly** [comment]
How long does it usually take?

**Comment by fkiraly** [comment]
🕐 ?

**Comment by dhirschfeld** [comment]
Because this recipe defines a `sktime-all-extras` package I think we have to wait until all the deps of that package are also available.

**Comment by fkiraly** [comment]
augh...

How about we also make the `sktime-all-extras` packages conditional?

I've laboriously worked out which packages are 3.11 compatible among the soft dependencies:
https://github.com/sktime/sktime/pull/4269

Would it be the same on `conda`, or would we expect the set to be strictly smaller?

We could also go with the approach we took on 0.16.1 (on `pypi`), just have none of the soft deps on 3.11, or only those we are certain support 3.11, then add them slowly back.

**Comment by dhirschfeld** [comment]
If you're desperate to get a version out supporting py3.11 you could comment out the all-extras package temporarily and create a PR to add it back after the core package has been published for 3.11.

**Comment by fkiraly** [comment]
Well, this is not desperation but rather trying to be user oriented...

What I meant is not commenting out the all-extras, but just adding "only on python 3.10 and lower" conditionals to the likely culprits, just like we did with `numba`.

**Comment by fkiraly** [comment]
@dhirschfeld, @giswqs, @yarnabrina, any ideas why rerender does not add 3.11 in the CI?

There is no longer a restriction in 0.18.0, and `numba` is a soft dependency.

See https://github.com/conda-forge/sktime-feedstock

**Comment by fkiraly** [comment]
FINALLY addresed by https://github.com/conda-forge/sktime-feedstock/pull/81
