### ISSUE TITLE
Release v0.6.1 not auto-updated

### ISSUE THREAD

**Issue by mloning** [conda-forge/sktime-feedstock#7]
Hi @dhirschfeld, do you have an idea why the PR wasn't created to automatically update the release to v0.6.1?

**Comment by dhirschfeld** [comment]
Maybe just takes a while - looks like it's there now?

**Comment by dhirschfeld** [comment]
If you need it faster it's easy enough to manually open a PR - just update the version, the hash and the deps.

**Comment by mloning** [comment]
Sure, thanks, wasn't sure if something was broken (seems like GitHub Actions was doing maintenance yesterday, a few actions didn't run until later that night)
