### ISSUE TITLE
0.21.1 release failing on main

### ISSUE THREAD

**Issue by fkiraly** [conda-forge/sktime-feedstock#98]
### Issue

It seems the tests on main are now failing, for 0.21.1.

From the logs, it seems like a dependency conflict.

What is odd is that the tests passed on the automated 0.21.1 PR.

FYI @yarnabrina, @dhirschfeld, @freddyaboulton

**Comment by yarnabrina** [comment]
Can you please link the failure? To me, it shows a green tick on main.

**Comment by fkiraly** [comment]
what? Am I going mad?

I also see the green tick now, yesterday evening everything was failing. I suppose, just a temporary issue?

**Comment by fkiraly** [comment]
closing, as it seems fixed.
